#!/usr/bin/env bash
# Generated by runcard from run 1l2y-rep4 — post-MD analysis.
# Reproduces the card's MM-GBSA binding free energy from the trajectory run.sh produces:
#   1. dry complex / receptor / ligand topologies from comp_oct.top
#   2. strip waters and ions from the production trajectory
#   3. MM-GBSA, single-trajectory, no entropy term
set -euo pipefail
cd "$(dirname "$0")"

MD="$(cd "$(dirname "$0")/md" && pwd)"
mkdir -p analysis && cd analysis

echo "[1/4] dry topologies (mbondi radii, read from this run's archived topology)" >&2
ante-MMPBSA.py \
  -p "$MD/comp_oct.top" \
  -c complex_dry.top \
  -r receptor.top \
  -l ligand.top \
  -s ':WAT,Na+,Cl-,K+' \
  -m ':1-20' \
  --radii=mbondi
# -m and -n are mutually exclusive in ante-MMPBSA.py. Passing the receptor mask as -m makes
# the ligand default to !(:1-20) == :21, which is exactly what this card recorded.

echo "[2/4] strip solvent -> traj.nc" >&2
cat > strip.cpptraj <<EOF
parm $MD/comp_oct.top
trajin $MD/product.nc
strip :WAT,Na+,Cl-,K+
autoimage
trajout traj.nc netcdf
go
quit
EOF
cpptraj -i strip.cpptraj

echo "[3/4] MM-GBSA" >&2
MMPBSA.py -O \
  -i ../analysis/mmgbsa.in \
  -o mmgbsa.dat \
  -cp complex_dry.top \
  -rp receptor.top \
  -lp ligand.top \
  -y traj.nc

echo "[4/4] representative structure (optional; becomes the card's 3D view)" >&2
mkdir -p cluster && cd cluster
cat > cluster.cpptraj <<EOF
parm ../complex_dry.top
trajin ../traj.nc
rms first :1-20&!@H=
cluster C0 hieragglo epsilon 2.0 averagelinkage rms :1-20&!@H= out cnumvtime.dat summary summary.dat repout rep repfmt pdb
go
quit
EOF
cpptraj -i cluster.cpptraj || true

echo "--- DELTA TOTAL ---" >&2
grep -A3 "DELTA TOTAL" ../mmgbsa.dat >&2 || tail -25 ../mmgbsa.dat >&2
